### ISSUE TITLE
Remocao das letras 'i' e 'u' da lista de palavras a nao serem capitalizadas

### ISSUE THREAD

**Issue by marcospcury** [ranpa/capitalize-pt-br#14]
Os caracteres 'i' e 'u' nao devem ser desconsiderados da capitalizacao pois nao sao preposicoes, o que impacta a capitalizacao de numerais romanos, por exemplo

**Comment by lira** [comment]
:cry: @ranpa resolve ae pls

**Comment by ranpa** [comment]
Olá, pessoal

Primeiramente gostaria de agradecer a interação a contribuição com o projeto.

Desculpem a demora pra dar uma resposta nessa issue. Acabei não recebendo a notificação por e-mail e acabei perdendo os acontecimentos.

Removi os caracteres 'i' e 'u' da lista `keepLowercase` e essa alteração entrou na versão 0.5.0.

Isso, porém, não soluciona a capitalização de algarismos romanos. Por exemplo, D. PEDRO I passa a ser D. Pedro I (como esperamos que seja), porém, D. PEDRO II continuará resultando em D. Pedro Ii.

Podemos abrir uma nova issue/PR pra tratar disso, caso surja necessidade. A solução para todos os algarismos romanos não é tão trivial. Fiquem à vontade para abrir uma PR, caso queiram contribuir para essa solução (agora as notificações já estão devidamente configuradas) :)
